id: PD5442D51
initial_creation_type: input
source_metadata:
  title: Vajracchedikā Prajñāpāramitā
  language: zh
  volumes:
    23a0c41b428e435fb49f25c1e64669a9:
      title: CIII_a
      base_file: CIII_a.txt
      work_id: W9F35FA8B
    8f4cab5048da4d4ba080e5cbbd9316d0:
      title: CIII_b
      base_file: CIII_b.txt
      work_id: WB0608D67
    a5687104016e4521b4897292f73d89f9:
      title: CIII_c
      base_file: CIII_c.txt
      work_id: W949C9108
    28f7b3e4354f444f945ba22605426ef5:
      title: CIII_d
      base_file: CIII_d.txt
      work_id: W0872B048
    75fffce056e842648dc83d8db234ceae:
      title: CIII_e
      base_file: CIII_e.txt
      work_id: W37A5E37D
    99034e1007a14d909103558886d735fd:
      title: CII_a
      base_file: CII_a.txt
      work_id: W4808EC41
    86ad6d1c9f724ca8af04a44c715a0f4d:
      title: CII_b
      base_file: CII_b.txt
      work_id: WFF1F623B
    183b974a48b644f786c1d0e5f248fd33:
      title: CII_c
      base_file: CII_c.txt
      work_id: WD049E219
    5cc6856bb29f40d994b71b46efc9806b:
      title: CIV_a
      base_file: CIV_a.txt
      work_id: WD7414DBA
    14c6486bea9646d696f6eb647ab73ab7:
      title: CIV_b
      base_file: CIV_b.txt
      work_id: W3AC44CCD
    64da25f21a084b5d8ea0067d3055ab54:
      title: CIV_c
      base_file: CIV_c.txt
      work_id: WD6C2B893
    875aa8bdb67a4a509f9fc97efd793473:
      title: CIV_d
      base_file: CIV_d.txt
      work_id: W9E21E788
    35268beb41d442879ed74ddc8b1d5910:
      title: CIV_e
      base_file: CIV_e.txt
      work_id: W422EC714
    9013e13d484e4982bb402f762a48015e:
      title: CIV_f
      base_file: CIV_f.txt
      work_id: WAAD794C2
    1c3a55da38454e06a3738bbfc92e3e1f:
      title: CIV_g
      base_file: CIV_g.txt
      work_id: WE8C5EFC5
    32389a217580405792e33c29d509943d:
      title: CIV_h
      base_file: CIV_h.txt
      work_id: W90800A31
    8aa1fbb69ca847b5972cbb02a1bcfeda:
      title: CIX_a
      base_file: CIX_a.txt
      work_id: W2EF44D2D
    b3ac58a9e6ec4080b6dc28e5001247d5:
      title: CIX_b
      base_file: CIX_b.txt
      work_id: WFA168A59
    82542095f9e3431c8ba434dfda4e5696:
      title: CI_a
      base_file: CI_a.txt
      work_id: WC5BB1560
    18c9c224743d4bf2b1f755529761c8e8:
      title: CI_b
      base_file: CI_b.txt
      work_id: WDFBC3DD2
    36f6948198784b658a30d38e527c362f:
      title: CI_c
      base_file: CI_c.txt
      work_id: WAB6AEE1A
    f2b7497bf36a40e0afa943e6640f521b:
      title: CI_d
      base_file: CI_d.txt
      work_id: W003C5D3D
    acbded8b49bc4a2a8a68538d95abd92f:
      title: CI_e
      base_file: CI_e.txt
      work_id: W7560B6BC
    6dcdb2f44b574caa8b753cebdc5f51e9:
      title: CVIII_a
      base_file: CVIII_a.txt
      work_id: W98983A88
    3e15030f06424055bb89a9bd939e837d:
      title: CVIII_b
      base_file: CVIII_b.txt
      work_id: WF9850652
    79ff8a1d4590443293819cfaac73379f:
      title: CVII_a
      base_file: CVII_a.txt
      work_id: WEC98ACA3
    4e6354c5106c4c7c9aca1e924084a639:
      title: CVII_b
      base_file: CVII_b.txt
      work_id: W28837F30
    763f1f62d0f54634abb429cdd778c187:
      title: CVII_c
      base_file: CVII_c.txt
      work_id: WD0541AF5
    420b96196e2b49509dd59afb0aa8b6f8:
      title: CVII_d
      base_file: CVII_d.txt
      work_id: W985A0BE2
    e0e01b3a20264c8bb028963a1cdfe8b4:
      title: CVII_e
      base_file: CVII_e.txt
      work_id: WD9CAC552
    2689f1a4f3174c17baa745ad4dacb355:
      title: CVII_f
      base_file: CVII_f.txt
      work_id: WAC00507D
    b0b73608b97d451ca59e907744e092e7:
      title: CVII_g
      base_file: CVII_g.txt
      work_id: WFB496804
    38134130baa642a2a234a97163b58435:
      title: CVII_h
      base_file: CVII_h.txt
      work_id: W5C7A0EBB
    0a945db321884581804359495e73ad41:
      title: CVI_a
      base_file: CVI_a.txt
      work_id: W751A0B99
    684b1bb129b241cb8f903a284574a0e7:
      title: CVI_b
      base_file: CVI_b.txt
      work_id: W294A3323
    c8efe8cc9b3c492185ef0beaa1a5c9b4:
      title: CVI_c
      base_file: CVI_c.txt
      work_id: WA120C4F0
    9ea048fd952e4179ba82926c3f67eed2:
      title: CV_a
      base_file: CV_a.txt
      work_id: W7A966AE1
    f9816829e5ae4beb91cbf840aa59f4c4:
      title: CV_b
      base_file: CV_b.txt
      work_id: W3E3AEC1C
    918f3b182d444e1bac91690b216139d7:
      title: CV_c
      base_file: CV_c.txt
      work_id: WC28239D3
    e55a0537584d42b79acb647dcd7d98e5:
      title: CXIII_a
      base_file: CXIII_a.txt
      work_id: W1D3FED4E
    f80ecf52ad16492eb1e3e2cdac48a1cd:
      title: CXIII_b
      base_file: CXIII_b.txt
      work_id: W671D0699
    4ea84f8b6bcc4a35bf04803e4a7320c3:
      title: CXII_a
      base_file: CXII_a.txt
      work_id: WB0DDD6D0
    2a174a39c5f143bcab6415d6f6df0d22:
      title: CXII_b
      base_file: CXII_b.txt
      work_id: WF5ABFB39
    ca54b4ebd01c4223a4249184a28e1ff1:
      title: CXIV_a
      base_file: CXIV_a.txt
      work_id: WB41F091D
    1b601c9c7f5846c98402df245c5c983a:
      title: CXIV_b
      base_file: CXIV_b.txt
      work_id: W4FF66694
    8707a334105844328f24b0111231fbdb:
      title: CXI_a
      base_file: CXI_a.txt
      work_id: W4BB4084C
    614bf051a36c4f0e8b02f264e97db83b:
      title: CXV_a
      base_file: CXV_a.txt
      work_id: W80833A84
    6f637386ee744fb381b75a69ba28bde1:
      title: CXV_b
      base_file: CXV_b.txt
      work_id: W4FDFEC48
    b1d923f7251e4de681031eda6d93ee68:
      title: CX_a
      base_file: CX_a.txt
      work_id: WFCCAC01D
    a290694fdafe4576a43bb9cab4c4a780:
      title: CX_b
      base_file: CX_b.txt
      work_id: W6F703CD9
    1e2593f7a5344f3e80f293a98e3fe206:
      title: Colophon
      base_file: Colophon.txt
      work_id: W07D67547
    87d1210d0db5434eb7f07917ce641e36:
      title: Preface
      base_file: Preface.txt
      work_id: W09EC0E9A
    d34df23bfcd3482caf25cf796a649adc:
      title: Title
      base_file: Title.txt
      work_id: W1AAC74BD
    3f93c5918563444e9c1910af31ecac6e:
      title: §1
      base_file: §1.txt
      work_id: WFA9EDDFB
    b0870f1b27074345996c51750786abe0:
      title: §11
      base_file: §11.txt
      work_id: W64FCC649
    b4fcab857cd147f98cd6f69acf4728ed:
      title: §12
      base_file: §12.txt
      work_id: W01BAFC11
    1980e8f7faff440ba29783c89d5d577d:
      title: §2
      base_file: §2.txt
      work_id: WDFC16427
    64a3c8edb09a4926ac3a2733c11b4b86:
      title: §23
      base_file: §23.txt
      work_id: W8C8297A0
    524dc3457a6d4ddf955e4a75a118dfb0:
      title: §24
      base_file: §24.txt
      work_id: WD1C8B9CD
    831da689a7f04b1c986b507e79208d77:
      title: §25
      base_file: §25.txt
      work_id: W884D3A1D
    23bee6d3487441e083860ee21d43139a:
      title: §27
      base_file: §27.txt
      work_id: WFC84F923
    f2af9d0bfa634cf8b00eca9013f25e68:
      title: §28
      base_file: §28.txt
      work_id: W88FDBB50
    197e80d64b1643c4aa4ad3e10d0e388e:
      title: §29
      base_file: §29.txt
      work_id: WA54AFA51
    6f5d74a0c80847a0852988c91e7e94ec:
      title: §3
      base_file: §3.txt
      work_id: WC6BA1241
    73a19fe574bc4aa7944ee481d69653cc:
      title: §4
      base_file: §4.txt
      work_id: W0413F233
    250a9374516b44229990161c8ea5d230:
      title: §5
      base_file: §5.txt
      work_id: W3B57BC44
    ed4c1dec0a1e465c8acb1e86da8ca90a:
      title: §6
      base_file: §6.txt
      work_id: W3E040ED3
    257c625ab04d4661bb95ef00fff9e611:
      title: §7
      base_file: §7.txt
      work_id: W6DADB1D2
    0cd2116ef14743209090edcdcf2da9c6:
      title: §8
      base_file: §8.txt
      work_id: W86A7CAC7
  chapter_to_tile:
    CI: §9
    CII: §10
    CIII: §13
    CIV: §14
    CV: §15
    CVI: §16
    CVII: §17
    CVIII: §18
    CIX: §19
    CX: §21
    CXI: §22
    CXII: §26
    CXIII: §30
    CXIV: §31
    CXV: §32
created_at: '2022-03-01T21:55:09.819222'
last_modified_at: '2022-03-01T21:55:09.819231'
